polls/modules/users/urls.py
from django.conf.urls import url

from .views import UserProfileView, SessionView


urlpatterns = [
    url(r'^$', UserProfileView.as_view(), name='index'),
    url(r'^session/$', SessionView.as_view(), name='session')
]

polls/modules/web/urls.py
from django.conf.urls import url

from .views import IndexView


urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index')
]

polls/polls/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('modules.web.urls', namespace='web')),
    url(r'^users/', include('modules.users.urls', namespace='users'))
]

polls/modules/users/models.py
from django.db import models

# Create your models here.

polls/modules/web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200, null=False)
    pub_date = models.DateTimeField(null=False, default=timezone.now)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=False)
    choice_text = models.CharField(max_length=200, null=False)


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=False)
    answer_date = models.DateTimeField(null=False, default=timezone.now)

polls/modules/base/forms.py
from django import forms


class PollsFormMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PollsFormMixin, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.TextInput):
                classes = set()

                widget_class = field.widget.attrs.get('class')
                if widget_class:
                    classes = {widget_class.split(' ')}

                classes.add('form-control')
                field.widget.attrs['class'] = ' '.join(classes)

polls/modules/users/forms.py
from django import forms
from django.contrib.auth.forms import User

from modules.base.forms import PollsFormMixin


class UserProfileForm(PollsFormMixin):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']

polls/modules/users/views.py
from collections import defaultdict
import json

from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.generic import View


class SessionView(View):
    # def get(self, request, *args, **kwargs):
    #     return c

    def post(self, request):
        error_message = defaultdict(str)

        username = request.POST.get('username')
        if not username:
            error_message['username'] = 'Username is required.'

        password = request.POST.get('password')
        if not password:
            error_message['password'] = 'Password is required.'

        data = {'status': 'ok'}

        if error_message:
            data = {
                'status': 'error',
                'errors': error_message
            }

        return JsonResponse(data)


class UserProfileView(View):
    param1 = 5
    user = None

    def get(self, request, *args, **kwargs):
        print(UserProfileView().param1)
        pass

    def post(self, request, *args, **kwargs):
        username = request.form.get('username')
        password = request.form.get('password')
        email = request.form.get('email')

        user = User.objects.create_user(username=username, password=password,
                                        email=email)

    def put(self, request, *args, **kwargs):
        # self.user = User(id=1)
        # self.clear()
        # self.validate()
        # self.save()

        pass

    def validate(self):
        pass

    def clear(self):
        pass

    def save(self):
        pass

polls/modules/web/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

polls/modules/web/templates/index.html
{% extends 'base.html' %}

{% block title %}Polls{% endblock %}

polls/templates/base.html
{% load static %}

{% spaceless %}
  <!doctype html>
  <html>

  <head>
    <title>{% block title %}{% endblock %}</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width">

    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>

    {% block styles %}
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
      <link rel="stylesheet" href="{% static 'css/base.css' %}" />

      <style>
      </style>
    {% endblock %}

    {% block scripts %}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.3/js.cookie.min.js"></script>

      <script>
        var csrfSafeMethod = function (method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        };

        $(document).ready(function () {
          $.ajaxSetup({
            beforeSend: function (xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                var csrfToken = Cookies.get('csrftoken');
                xhr.setRequestHeader("X-CSRFToken", csrfToken);
              }
            }
          });

          var auth_form = $('#auth-form');
          var resetErrors = function () {
            auth_form.find('.form-group')
              .removeClass('has-error')
              .find('.help-block')
              .html('');
          };

          auth_form.submit(function () {
            resetErrors();

            var onSuccess = function (resp) {
              auth_form.find('input[name=password]').val('');

              if (resp.status === 'error') {
                Object.keys(resp.errors).forEach(function (key) {
                  auth_form.find('input[name=' + key + ']')
                    .parent()
                    .addClass('has-error')
                    .find('.help-block')
                    .html(resp.errors[key]);
                });
              }
            };

            var data = {};
            auth_form.find('input').each(function () {
              var item = $(this);
              var value = item.val().trim();
              if (value.length !== 0) {
                data[item.attr('name')] = value;
              }
            });

            $.post(auth_form.attr('action'), data, onSuccess, 'json');
            return false;
          });

          $('#auth-dialog').on('hidden.bs.modal', function () {
            auth_form.find('.form-group input').val('');
            resetErrors();
          });
        });
      </script>
    {% endblock %}
  </head>

  <body>
    <nav id="main-nav" class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'web:index' %}">Polls</a>

          <div id="auth-container">
            <span class="navbar-text">Howdy, Guest</span>
            <button type="button" class="btn btn-default navbar-btn"
                    data-toggle="modal" data-target="#auth-dialog">
              Sign In
            </button>
          </div>
        </div>
      </div>
    </nav>

    <div class="clear"></div>

    <div id="auth-dialog" class="modal fade" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <form id="auth-form" action="{% url 'users:session' %}"
              class="modal-content">

          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"
                    aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title">Authentication</h4>
          </div>

          <div class="modal-body">
            <div class="form-group">
              {{ user_profile_form.username.label_tag }}
              {{ user_profile_form.username }}
              <div class="help-block"></div>
            </div>

            <div class="form-group">
              {{ user_profile_form.password.label_tag }}
              {{ user_profile_form.password }}
              <div class="help-block"></div>
            </div>

            <div class="sep bg-success text-center text-muted">
              Registration Email
            </div>

            <div class="form-group">
              {{ user_profile_form.email.label_tag }}
              {{ user_profile_form.email }}
              <div class="help-block"></div>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default"
                    data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Sign In</button>
          </div>
        </form>
      </div>
    </div>
  </body>

  </html>
{% endspaceless %}